import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "nexus-ai",
    name: "Nexus AI",
    description: "Advanced general intelligence with multi-modal processing capabilities",
    price: 2999,
    category: "Premium AI",
    modelPath: "/models/nexus-ai",
    features: ["Multi-Modal Processing", "Emotional Intelligence", "Advanced Reasoning", "Adaptive Learning"],
    capabilities: ["Natural Language Understanding", "Computer Vision", "Decision Making", "Creative Problem Solving"],
    popular: true,
    featured: true,
    rating: 4.9,
  },
  {
    id: "quantum-assistant",
    name: "Quantum Assistant",
    description: "Quantum computing specialist for complex calculations and optimization",
    price: 4999,
    category: "Quantum Computing",
    modelPath: "/models/quantum-assistant",
    features: ["Quantum Processing", "Superposition Analysis", "Entanglement Optimization", "Quantum Algorithms"],
    capabilities: ["Complex Calculations", "Cryptography", "Optimization Problems", "Scientific Research"],
    popular: false,
    featured: true,
    rating: 4.8,
  },
  {
    id: "cyber-guardian",
    name: "Cyber Guardian",
    description: "Advanced cybersecurity AI for threat detection and response",
    price: 3499,
    category: "Cybersecurity",
    modelPath: "/models/cyber-guardian",
    features: ["Threat Detection", "Real-time Monitoring", "Incident Response", "Vulnerability Assessment"],
    capabilities: ["Malware Analysis", "Network Security", "Data Protection", "Compliance Monitoring"],
    popular: true,
    featured: false,
    rating: 4.7,
  },
  {
    id: "data-analyst",
    name: "Data Analyst Pro",
    description: "Intelligence analytics engine for data insights and predictions",
    price: 2299,
    category: "Data Analytics",
    modelPath: "/models/data-analyst",
    features: ["Predictive Analytics", "Data Visualization", "Pattern Recognition", "Automated Reporting"],
    capabilities: ["Statistical Analysis", "Machine Learning", "Business Intelligence", "Data Mining"],
    popular: false,
    featured: true,
    rating: 4.6,
  },
  {
    id: "creative-ai",
    name: "Creative Spark",
    description: "Artistic intelligence engine for creative content generation",
    price: 1899,
    category: "Creative AI",
    modelPath: "/models/creative-ai",
    features: ["Content Generation", "Artistic Creation", "Music Composition", "Story Writing"],
    capabilities: ["Digital Art", "Creative Writing", "Design Concepts", "Innovation Support"],
    popular: true,
    featured: false,
    rating: 4.5,
  },
  {
    id: "automation-bot",
    name: "Automation Master",
    description: "Process optimization engine for workflow automation",
    price: 1699,
    category: "Automation",
    modelPath: "/models/automation-bot",
    features: ["Workflow Automation", "Process Optimization", "System Integration", "Task Scheduling"],
    capabilities: ["RPA Implementation", "API Integration", "Workflow Design", "Performance Monitoring"],
    popular: false,
    featured: true,
    rating: 4.4,
  },
]

export const featuredProducts = products.filter((product) => product.featured)
export const popularProducts = products.filter((product) => product.popular)
